# Kay Sweebe
# CS370
# Lab 2.1
#
# 1. Lex file
# Lex lab2remove.l  outputs lex.yy.c
# 2. Compile file
# gcc -o remove lex.yy.c outputs remove

all:
# lex file
	lex lab2remove.l
# compile file
	gcc -o remove lex.yy.c
